name: "💡 [INFO ONLY] Checklist Tracker"

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Checklist Completion
        uses: seaduboi/todo-checker-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

